spring:
  config:
    activate:
      on-profile: default
  application:
    name: grpc-server
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

grpc:
  server:
    port: 9090