spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logbook:
  include:
    - /v1/product/**
  filter.enabled: true
  secure-filter.enabled: true
  obfuscate:
    headers:
    parameters:

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE