# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x08tutorial\"I\n\x12\x43reateOrderRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12#\n\x08products\x18\x02 \x03(\x0b\x32\x11.tutorial.Product\"C\n\x13\x43reateOrderResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12 \n\x06status\x18\x02 \x01(\x0e\x32\x10.tutorial.Status\"G\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02*;\n\x06Status\x12\x0b\n\x07\x43REATED\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x12\x0c\n\x08\x43\x41NCELED\x10\x02\x12\x0c\n\x08RETURNED\x10\x03\x32[\n\x12\x43reateOrderService\x12\x45\n\x06\x63reate\x12\x1c.tutorial.CreateOrderRequest\x1a\x1d.tutorial.CreateOrderResponseB\x1b\n\x17\x63om.example.demo.protosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.example.demo.protosP\001'
  _globals['_STATUS']._serialized_start=242
  _globals['_STATUS']._serialized_end=301
  _globals['_CREATEORDERREQUEST']._serialized_start=25
  _globals['_CREATEORDERREQUEST']._serialized_end=98
  _globals['_CREATEORDERRESPONSE']._serialized_start=100
  _globals['_CREATEORDERRESPONSE']._serialized_end=167
  _globals['_PRODUCT']._serialized_start=169
  _globals['_PRODUCT']._serialized_end=240
  _globals['_CREATEORDERSERVICE']._serialized_start=303
  _globals['_CREATEORDERSERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
